// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Data.Models;

public partial class Bagitem
{
    public int BagItemId { get; set; }

    public int? BagId { get; set; }

    public int? ItemId { get; set; }

    public int? Quantity { get; set; }

    public DateTime? AddedAt { get; set; }

    public virtual Bag Bag { get; set; }

    public virtual Item Item { get; set; }
}