// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Data.Models;

public partial class Dailyrewardclaim
{
    public int ClaimId { get; set; }

    public int? UserId { get; set; }

    public int? DailyId { get; set; }

    public int? TaskId { get; set; }

    public DateTime? ClaimedAt { get; set; }

    public virtual Task Task { get; set; }

    public virtual User User { get; set; }
}