// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Data.Models;

public partial class Tradestatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<Tradehistory> Tradehistories { get; set; } = new List<Tradehistory>();
}