// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Data.Models;

public partial class Tradehistory
{
    public int TradeId { get; set; }

    public int? UserAid { get; set; }

    public int? UserBid { get; set; }

    public int? UserTreeAid { get; set; }

    public int? UserTreeBid { get; set; }

    public decimal? TradeFee { get; set; }

    public int? StatusId { get; set; }

    public DateTime? RequestedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual Tradestatus Status { get; set; }

    public virtual User UserA { get; set; }

    public virtual User UserB { get; set; }

    public virtual Usertree UserTreeA { get; set; }

    public virtual Usertree UserTreeB { get; set; }
}