// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZenGarden.Infrastructure.Persistence;

#nullable disable

namespace ZenGarden.Infrastructure.Migrations
{
    [DbContext(typeof(ZenGardenContext))]
    [Migration("20250305114859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ZenGarden.Domain.Entities.Bag", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("Bag");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.BagItem", b =>
                {
                    b.Property<int>("BagItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BagItemID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BagItemId"));

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("BagId")
                        .HasColumnType("int")
                        .HasColumnName("BagID");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BagItemId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BagId" }, "BagID");

                    b.HasIndex(new[] { "ItemId" }, "ItemID");

                    b.ToTable("BagItem");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.FocusMethod", b =>
                {
                    b.Property<int>("FocusMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FocusMethodID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FocusMethodId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DefaultBreak")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultDuration")
                        .HasColumnType("int");

                    b.Property<int?>("MaxBreak")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDuration")
                        .HasColumnType("int");

                    b.Property<int?>("MinBreak")
                        .HasColumnType("int");

                    b.Property<int?>("MinDuration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("FocusMethodId")
                        .HasName("PRIMARY");

                    b.ToTable("FocusMethod");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("Limited")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rarity")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ItemId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Type", "Rarity" }, "idx_item_type_rarity");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.ItemDetail", b =>
                {
                    b.Property<int?>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    b.Property<int?>("Cooldown")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("DurationType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("MaxStack")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .HasColumnType("json");

                    b.Property<string>("SpecialEffects")
                        .HasColumnType("text");

                    b.Property<string>("Stats")
                        .HasColumnType("json");

                    b.Property<string>("Tags")
                        .HasColumnType("json");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("ItemId")
                        .HasName("PRIMARY");

                    b.ToTable("ItemDetail");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Leaderboard", b =>
                {
                    b.Property<int>("LeaderboardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LeaderboardID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LeaderboardId"));

                    b.Property<int?>("BestTrees")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<int?>("ProductivityScore")
                        .HasColumnType("int");

                    b.Property<int?>("TotalTrees")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LeaderboardId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "UserID1");

                    b.ToTable("Leaderboard");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Packages", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PackageID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("PackageId")
                        .HasName("PRIMARY");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.PurchaseHistory", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PurchaseID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PurchaseId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ItemId" }, "ItemID2");

                    b.HasIndex(new[] { "UserId" }, "UserID2");

                    b.ToTable("PurchaseHistory");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.TaskFocusSetting", b =>
                {
                    b.Property<int>("TaskFocusSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TaskFocusSettingId"));

                    b.Property<int?>("CustomBreak")
                        .HasColumnType("int");

                    b.Property<int?>("CustomDuration")
                        .HasColumnType("int");

                    b.Property<int>("FocusMethodId")
                        .HasColumnType("int");

                    b.Property<int>("SuggestedBreak")
                        .HasColumnType("int");

                    b.Property<int>("SuggestedDuration")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("TaskFocusSettingId");

                    b.HasIndex("FocusMethodId");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("TaskFocusSetting");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Tasks", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaskID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("AiProcessedDescription")
                        .HasColumnType("text")
                        .HasColumnName("AIProcessedDescription");

                    b.Property<DateTime?>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("text");

                    b.Property<string>("TaskName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TimeOverdue")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("UserTreeID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("TaskId")
                        .HasName("PRIMARY");

                    b.HasIndex("UserTreeID");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex(new[] { "UserId" }, "idx_task_user");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.TradeHistory", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TradeID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TradeId"));

                    b.Property<DateTime?>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TradeFee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int?>("UserAid")
                        .HasColumnType("int")
                        .HasColumnName("UserAID");

                    b.Property<int?>("UserBid")
                        .HasColumnType("int")
                        .HasColumnName("UserBID");

                    b.Property<int?>("UserTreeAid")
                        .HasColumnType("int")
                        .HasColumnName("UserTreeAID");

                    b.Property<int?>("UserTreeBid")
                        .HasColumnType("int")
                        .HasColumnName("UserTreeBID");

                    b.HasKey("TradeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserBid" }, "UserBID");

                    b.HasIndex(new[] { "UserTreeAid" }, "UserTreeAID");

                    b.HasIndex(new[] { "UserTreeBid" }, "UserTreeBID");

                    b.HasIndex(new[] { "UserAid", "UserBid" }, "idx_tradehistory_user");

                    b.ToTable("TradeHistory");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Transactions", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PackageId" }, "idx_transaction_package");

                    b.HasIndex(new[] { "UserId" }, "idx_transaction_user");

                    b.HasIndex(new[] { "WalletId" }, "idx_transaction_wallet");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.TreeLevelConfig", b =>
                {
                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Level"));

                    b.Property<int>("XpRequired")
                        .HasColumnType("int");

                    b.HasKey("Level");

                    b.ToTable("TreeLevelConfig");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.TreeType", b =>
                {
                    b.Property<int>("TreeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TreeTypeID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TreeTypeId"));

                    b.Property<decimal?>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rarity")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TreeTypeId")
                        .HasName("PRIMARY");

                    b.ToTable("TreeType");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.TreeXpLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserTreeId")
                        .HasColumnType("int");

                    b.Property<int>("XpAmount")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserTreeId");

                    b.ToTable("TreeXpLog");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.UserExperience", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<long>("TotalXp")
                        .HasColumnType("bigint")
                        .HasColumnName("TotalXP");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<int>("XpToNextLevel")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex("LevelId");

                    b.ToTable("UserExperience");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.UserLevelConfig", b =>
                {
                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Level"));

                    b.Property<int>("XpRequired")
                        .HasColumnType("int");

                    b.HasKey("Level");

                    b.ToTable("UserLevelConfig");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.UserTree", b =>
                {
                    b.Property<int>("UserTreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserTreeID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserTreeId"));

                    b.Property<int?>("FinalTreeId")
                        .HasColumnType("int")
                        .HasColumnName("FinalTreeID");

                    b.Property<int?>("FinalTreeRarity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("TotalXp")
                        .HasColumnType("int");

                    b.Property<int>("TreeLevel")
                        .HasColumnType("int");

                    b.Property<int>("TreeStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UserTreeId")
                        .HasName("PRIMARY");

                    b.HasIndex("FinalTreeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTree");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.UserXpLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("XpAmount")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("UserXpLog");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("OtpCodeHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("OtpExpiry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<decimal?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastTransactionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Workspace", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("Configuration")
                        .HasColumnType("json");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("Workspace");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.WorkspaceItem", b =>
                {
                    b.Property<int>("WorkspaceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WorkspaceItemID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkspaceItemId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Effect")
                        .HasColumnType("json");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("WorkspaceId")
                        .HasColumnType("int")
                        .HasColumnName("WorkspaceID");

                    b.HasKey("WorkspaceItemId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ItemId" }, "ItemID3");

                    b.HasIndex(new[] { "WorkspaceId" }, "WorkspaceID");

                    b.HasIndex(new[] { "UserId" }, "idx_workspace_item_user");

                    b.ToTable("WorkspaceItem");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Bag", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Users", "User")
                        .WithOne("Bag")
                        .HasForeignKey("ZenGarden.Domain.Entities.Bag", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.BagItem", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Bag", "Bag")
                        .WithMany("BagItem")
                        .HasForeignKey("BagId")
                        .HasConstraintName("bagitem_ibfk_1");

                    b.HasOne("ZenGarden.Domain.Entities.Item", "Item")
                        .WithMany("BagItem")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("bagitem_ibfk_2");

                    b.Navigation("Bag");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.ItemDetail", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Item", "Item")
                        .WithOne("ItemDetail")
                        .HasForeignKey("ZenGarden.Domain.Entities.ItemDetail", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Leaderboard", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Users", "User")
                        .WithMany("Leaderboard")
                        .HasForeignKey("UserId")
                        .HasConstraintName("leaderboard_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.PurchaseHistory", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Item", "Item")
                        .WithMany("PurchaseHistory")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("purchasehistory_ibfk_2");

                    b.HasOne("ZenGarden.Domain.Entities.Users", "User")
                        .WithMany("PurchaseHistory")
                        .HasForeignKey("UserId")
                        .HasConstraintName("purchasehistory_ibfk_1");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.TaskFocusSetting", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.FocusMethod", "FocusMethod")
                        .WithMany("TaskFocusSettings")
                        .HasForeignKey("FocusMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenGarden.Domain.Entities.Tasks", "Task")
                        .WithOne("TaskFocusSetting")
                        .HasForeignKey("ZenGarden.Domain.Entities.TaskFocusSetting", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FocusMethod");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Tasks", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Users", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .HasConstraintName("tasks_ibfk_1");

                    b.HasOne("ZenGarden.Domain.Entities.UserTree", "UserTree")
                        .WithMany()
                        .HasForeignKey("UserTreeID");

                    b.HasOne("ZenGarden.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkspaceId");

                    b.Navigation("User");

                    b.Navigation("UserTree");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.TradeHistory", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Users", "UserA")
                        .WithMany("TradeHistoryUserA")
                        .HasForeignKey("UserAid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZenGarden.Domain.Entities.Users", "UserB")
                        .WithMany("TradeHistoryUserB")
                        .HasForeignKey("UserBid")
                        .HasConstraintName("tradehistory_ibfk_2");

                    b.HasOne("ZenGarden.Domain.Entities.UserTree", "UserTreeA")
                        .WithMany("TradeHistoryUserTreeA")
                        .HasForeignKey("UserTreeAid")
                        .HasConstraintName("tradehistory_ibfk_3");

                    b.HasOne("ZenGarden.Domain.Entities.UserTree", "UserTreeB")
                        .WithMany("TradeHistoryUserTreeB")
                        .HasForeignKey("UserTreeBid")
                        .HasConstraintName("tradehistory_ibfk_4");

                    b.Navigation("UserA");

                    b.Navigation("UserB");

                    b.Navigation("UserTreeA");

                    b.Navigation("UserTreeB");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Transactions", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Packages", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_ibfk_3");

                    b.HasOne("ZenGarden.Domain.Entities.Users", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("transactions_ibfk_1");

                    b.HasOne("ZenGarden.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .HasConstraintName("transactions_ibfk_2");

                    b.Navigation("Package");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.TreeXpLog", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Tasks", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenGarden.Domain.Entities.UserTree", "UserTree")
                        .WithMany()
                        .HasForeignKey("UserTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("UserTree");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.UserExperience", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.UserLevelConfig", "UserLevelConfig")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenGarden.Domain.Entities.Users", "User")
                        .WithOne("UserExperience")
                        .HasForeignKey("ZenGarden.Domain.Entities.UserExperience", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserLevelConfig");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.UserTree", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.TreeType", "FinalTree")
                        .WithMany("UserTree")
                        .HasForeignKey("FinalTreeId");

                    b.HasOne("ZenGarden.Domain.Entities.Users", "User")
                        .WithMany("UserTree")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("usertree_ibfk_1");

                    b.Navigation("FinalTree");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.UserXpLog", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Users", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("users_ibfk_1");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Users", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("ZenGarden.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Users", "User")
                        .WithOne("Workspace")
                        .HasForeignKey("ZenGarden.Domain.Entities.Workspace", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.WorkspaceItem", b =>
                {
                    b.HasOne("ZenGarden.Domain.Entities.Item", "Item")
                        .WithMany("WorkspaceItem")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("workspaceitem_ibfk_2");

                    b.HasOne("ZenGarden.Domain.Entities.Users", "User")
                        .WithMany("WorkspaceItem")
                        .HasForeignKey("UserId")
                        .HasConstraintName("workspaceitem_ibfk_3");

                    b.HasOne("ZenGarden.Domain.Entities.Workspace", "Workspace")
                        .WithMany("WorkspaceItem")
                        .HasForeignKey("WorkspaceId")
                        .HasConstraintName("workspaceitem_ibfk_1");

                    b.Navigation("Item");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Bag", b =>
                {
                    b.Navigation("BagItem");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.FocusMethod", b =>
                {
                    b.Navigation("TaskFocusSettings");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Item", b =>
                {
                    b.Navigation("BagItem");

                    b.Navigation("ItemDetail");

                    b.Navigation("PurchaseHistory");

                    b.Navigation("WorkspaceItem");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Tasks", b =>
                {
                    b.Navigation("TaskFocusSetting");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.TreeType", b =>
                {
                    b.Navigation("UserTree");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.UserTree", b =>
                {
                    b.Navigation("TradeHistoryUserTreeA");

                    b.Navigation("TradeHistoryUserTreeB");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Users", b =>
                {
                    b.Navigation("Bag");

                    b.Navigation("Leaderboard");

                    b.Navigation("PurchaseHistory");

                    b.Navigation("Tasks");

                    b.Navigation("TradeHistoryUserA");

                    b.Navigation("TradeHistoryUserB");

                    b.Navigation("Transactions");

                    b.Navigation("UserExperience");

                    b.Navigation("UserTree");

                    b.Navigation("Wallet");

                    b.Navigation("Workspace");

                    b.Navigation("WorkspaceItem");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ZenGarden.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("WorkspaceItem");
                });
#pragma warning restore 612, 618
        }
    }
}
