// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZenGarden.Domain.Entities;

public partial class Bag
{
    [Key, ForeignKey("User")]
    public int UserId { get; set; }

    public int? Capacity { get; set; } = 100;

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<BagItem> BagItem { get; set; } = new List<BagItem>();

    public virtual Users User { get; set; }
}