// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class BagItem
{
    public int BagItemId { get; set; }

    public int? BagId { get; set; }

    public int? ItemId { get; set; }

    public int? Quantity { get; set; }

    public bool isEquipped { get; set; } = false;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    public virtual Bag Bag { get; set; }
    public virtual Item Item { get; set; }
}