// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class Dailyreward
{
    public int DailyId { get; set; }

    public int? Day { get; set; }

    public string Reward { get; set; }

    public string RewardType { get; set; }

    public int? ItemId { get; set; }

    public int? Quantity { get; set; }

    public string ConditionType { get; set; }

    public string ConditionValue { get; set; }

    public virtual Item Item { get; set; }
}