// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;
using ZenGarden.Domain.Enums;

namespace ZenGarden.Domain.Entities;

public partial class FocusActivity
{
    public int ActivityId { get; set; }
    public int TrackingId { get; set; }
    public FocusActivityType Type { get; set; }
    public string ActivityDetails { get; set; }
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    public bool IsDistraction { get; set; }
    public int? Duration { get; set; }  // Duration in seconds
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Navigation property
    public virtual FocusTracking FocusTracking { get; set; }
} 