// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using ZenGarden.Domain.Enums;

namespace ZenGarden.Domain.Entities;

public partial class FocusTracking
{
    public int TrackingId { get; set; }
    public int UserId { get; set; }
    public int TaskId { get; set; }
    public int FocusMethodId { get; set; }
    public DateTime StartTime { get; set; }
    public DateTime? EndTime { get; set; }
    public int PlannedDuration { get; set; }  // in minutes
    public int? ActualDuration { get; set; }  // in minutes
    public bool IsCompleted { get; set; }
    public string TrackingNote { get; set; }
    public double XpEarned { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    public FocusTrackingStatus Status { get; set; }

    // Navigation properties
    public virtual Users User { get; set; }
    public virtual Tasks Task { get; set; }
    public virtual FocusMethod FocusMethod { get; set; }
    public virtual ICollection<FocusActivity> FocusActivities { get; set; } = new List<FocusActivity>();
} 