// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class Item
{
    public int ItemId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string Rarity { get; set; }

    public decimal? Cost { get; set; }

    public bool? Limited { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Bagitem> Bagitem { get; set; } = new List<Bagitem>();

    public virtual ICollection<Dailyreward> Dailyreward { get; set; } = new List<Dailyreward>();

    public virtual Itemdetail Itemdetail { get; set; }

    public virtual ICollection<Purchasehistory> Purchasehistory { get; set; } = new List<Purchasehistory>();

    public virtual ICollection<Workspaceitem> Workspaceitem { get; set; } = new List<Workspaceitem>();
}