// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ZenGarden.Domain.Enums;

namespace ZenGarden.Domain.Entities;

public partial class PurchaseHistory
{
    public int PurchaseId { get; set; }

    public int? UserId { get; set; }

    public int? ItemId { get; set; }

    public decimal? TotalPrice { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    public PurchaseHistoryStatus Status { get; set; } = PurchaseHistoryStatus.Pending;

    public virtual Item Item { get; set; }

    public virtual Users User { get; set; }
}