// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class Taskstatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<Tasks> Tasks { get; set; } = new List<Tasks>();
}