// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ZenGarden.Domain.Enums;

namespace ZenGarden.Domain.Entities;

public partial class Transactions
{
    public int TransactionId { get; set; }
    public int? UserId { get; set; }
    public int? WalletId { get; set; }
    public int? PackageId { get; set; }

    public decimal? Amount { get; set; }
    public TransactionType Type { get; set; }
    public TransactionStatus Status { get; set; }
    public string PaymentMethod { get; set; } = "";
    public string TransactionRef { get; set; } = "";
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? CompletedAt { get; set; }

    public virtual Users User { get; set; }
    public virtual Wallet Wallet { get; set; }
    public virtual Packages Package { get; set; } 
}
