// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int? UserId { get; set; }

    public int? WalletId { get; set; }

    public decimal? Amount { get; set; }

    public string TransactionType { get; set; }

    public string Status { get; set; }

    public decimal? CommissionFee { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }

    public virtual Wallet Wallet { get; set; }
}