// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class TreeType
{
    public int TreeTypeId { get; set; }
    public string Name { get; set; }
    public string Rarity { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    public decimal? BasePrice { get; set; }

    public virtual ICollection<UserTree> UserTree { get; set; } = new List<UserTree>();
}