// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class Tree
{
    public int TreeId { get; set; }
    public string Name { get; set; }
    public string Rarity { get; set; }
    public string ImageUrl { get; set; }
    public string Description { get; set; }
    public bool IsActive { get; set; } = true;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    public virtual ICollection<UserTree> UserTree { get; set; } = new List<UserTree>();
    public virtual ICollection<TradeHistory> TradeHistoryDesiredTree { get; set; } = new List<TradeHistory>();
    
}