// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class User
{
    public int UserId { get; set; }

    public int? RoleId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Phone { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Bag> Bags { get; set; } = new List<Bag>();

    public virtual ICollection<Dailyrewardclaim> Dailyrewardclaims { get; set; } = new List<Dailyrewardclaim>();

    public virtual ICollection<Deposittransaction> Deposittransactions { get; set; } = new List<Deposittransaction>();

    public virtual ICollection<Leaderboard> Leaderboards { get; set; } = new List<Leaderboard>();

    public virtual ICollection<Purchasehistory> Purchasehistories { get; set; } = new List<Purchasehistory>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();

    public virtual ICollection<Tradehistory> TradehistoryUserAs { get; set; } = new List<Tradehistory>();

    public virtual ICollection<Tradehistory> TradehistoryUserBs { get; set; } = new List<Tradehistory>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual ICollection<Useractivity> Useractivities { get; set; } = new List<Useractivity>();

    public virtual ICollection<Userexperience> Userexperiences { get; set; } = new List<Userexperience>();

    public virtual ICollection<Usertree> Usertrees { get; set; } = new List<Usertree>();

    public virtual ICollection<Wallet> Wallets { get; set; } = new List<Wallet>();

    public virtual ICollection<Workspaceitem> Workspaceitems { get; set; } = new List<Workspaceitem>();

    public virtual ICollection<Workspace> Workspaces { get; set; } = new List<Workspace>();
}