// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class Users
{
    public int UserId { get; set; }

    public int? RoleId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Phone { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Bag> Bag { get; set; } = new List<Bag>();

    public virtual ICollection<Dailyrewardclaim> Dailyrewardclaim { get; set; } = new List<Dailyrewardclaim>();

    public virtual ICollection<Deposittransaction> Deposittransaction { get; set; } = new List<Deposittransaction>();

    public virtual ICollection<Leaderboard> Leaderboard { get; set; } = new List<Leaderboard>();

    public virtual ICollection<Purchasehistory> Purchasehistory { get; set; } = new List<Purchasehistory>();

    public virtual Roles Role { get; set; }

    public virtual ICollection<Tasks> Tasks { get; set; } = new List<Tasks>();

    public virtual ICollection<Tradehistory> TradehistoryUserA { get; set; } = new List<Tradehistory>();

    public virtual ICollection<Tradehistory> TradehistoryUserB { get; set; } = new List<Tradehistory>();

    public virtual ICollection<Transactions> Transactions { get; set; } = new List<Transactions>();

    public virtual ICollection<Useractivity> Useractivity { get; set; } = new List<Useractivity>();

    public virtual ICollection<Userexperience> Userexperience { get; set; } = new List<Userexperience>();

    public virtual ICollection<Usertree> Usertree { get; set; } = new List<Usertree>();

    public virtual ICollection<Wallet> Wallet { get; set; } = new List<Wallet>();

    public virtual ICollection<Workspace> Workspace { get; set; } = new List<Workspace>();

    public virtual ICollection<Workspaceitem> Workspaceitem { get; set; } = new List<Workspaceitem>();
}