// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZenGarden.Domain.Entities;

public partial class UserExperience
{
    public  int UserExperienceId { get; set; }
    public int UserId { get; set; }
    public long TotalXp { get; set; } = 0;
    public int XpToNextLevel { get; set; } = 100; 
    public int LevelId { get; set; } 
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    public virtual Users User { get; set; }
    public virtual UserXpConfig UserXpConfig { get; set; }
}