// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class Useractivity
{
    public int ActivityId { get; set; }

    public int? UserId { get; set; }

    public int? FocusMethodId { get; set; }

    public int? TaskId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int? SuggestedDuration { get; set; }

    public int? UserAdjustedDuration { get; set; }

    public int? SuggestedBreak { get; set; }

    public int? UserAdjustedBreak { get; set; }

    public int? Interruptions { get; set; }

    public int? MouseClicks { get; set; }

    public int? MouseScrolls { get; set; }

    public int? Keystrokes { get; set; }

    public int? ActiveTime { get; set; }

    public int? InactiveTime { get; set; }

    public int? FocusScore { get; set; }

    public int? WarningSpent { get; set; }

    public virtual Focusmethod FocusMethod { get; set; }

    public virtual Task Task { get; set; }

    public virtual User User { get; set; }
}