// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class Usertree
{
    public int UserTreeId { get; set; }

    public int? UserId { get; set; }

    public int? FinalTreeId { get; set; }

    public DateTime? PlantedAt { get; set; }

    public int? TreeLevel { get; set; }

    public int? Xp { get; set; }

    public string TreeStatus { get; set; }

    public string FinalTreeRarity { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual Treetype FinalTree { get; set; }

    public virtual ICollection<Tradehistory> TradehistoryUserTreeAs { get; set; } = new List<Tradehistory>();

    public virtual ICollection<Tradehistory> TradehistoryUserTreeBs { get; set; } = new List<Tradehistory>();

    public virtual ICollection<Treeprogress> Treeprogresses { get; set; } = new List<Treeprogress>();

    public virtual User User { get; set; }
}