// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections;
using System.Collections.Generic;
using ZenGarden.Domain.Enums;

namespace ZenGarden.Domain.Entities;

#nullable enable
public partial class UserTree
{
    public int UserTreeId { get; set; }
    public int? UserId { get; set; }
    public int? FinalTreeId { get; set; }
    public int? TreeOwnerId { get; set; }


    public required string Name { get; set; }
    public int LevelId { get; set; } = 1;
    public double TotalXp { get; set; } = 0;
    public bool IsMaxLevel { get; set; } = false;
    public TreeStatus TreeStatus { get; set; } = TreeStatus.Growing;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    public virtual Tree? FinalTree { get; set; }
    public virtual required TreeXpConfig TreeXpConfig { get; set; }

    public virtual ICollection<Tasks> Tasks { get; set; } = new List<Tasks>();
    public virtual required Users User { get; set; }
    public virtual required Users TreeOwner { get; set; }
}