// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZenGarden.Domain.Entities;

public partial class UserExperience
{
    [Key, ForeignKey("User")]
    public int UserId { get; set; }
    [Required]
    public long TotalXp { get; set; } = 0;

    public int CurrentLevel { get; set; } = 1;

    public int XpToNextLevel { get; set; } = 100; 

    public int LevelId { get; set; } 

    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("UserId")]
    public virtual Users User { get; set; }

    [ForeignKey("LevelId")]
    public virtual UserLevelConfig UserLevelConfig { get; set; }
}