// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZenGarden.Domain.Entities;

public partial class Workspaceitem
{
    public int WorkspaceItemId { get; set; }

    public int? WorkspaceId { get; set; }

    public int? ItemId { get; set; }

    public int? UserId { get; set; }

    public int? Quantity { get; set; }

    public string Effect { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Item Item { get; set; }

    public virtual Users User { get; set; }

    public virtual Workspace Workspace { get; set; }
}