// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZenGarden.Domain.Entities;

public partial class Workspace
{
    [Key]
    public int WorkspaceId { get; set; }
    [ForeignKey("UserId")]
    public int UserId { get; set; }

    public string Configuration { get; set; } = "{\"theme\": \"light\", \"notifications\": true, \"layout\": \"grid\", \"widgets\": []}";

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Users User { get; set; }
    
    public virtual ICollection<Tasks> Tasks { get; set; } = new List<Tasks>();

    public virtual ICollection<WorkspaceItem> WorkspaceItem { get; set; } = new List<WorkspaceItem>();
}