name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ZenGarden

      - name: Debug - Check files
        run: ls -R

      - name: Build project
        run: dotnet build ZenGarden --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ZenGarden --configuration Release --no-build --verbosity normal