name: Deploy to Azure Web App

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Hoặc version phù hợp với app bạn

      - name: Restore dependencies
        run: dotnet restore ZenGarden

      - name: Debug - Check files
        run: ls -R

      - name: Build project
        run: dotnet build ZenGarden --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ZenGarden --configuration Release --no-build --verbosity normal

      - name: Publish app
        run: dotnet publish ZenGarden -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: zengarden-api         # Tên Web App trên Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
